FROM nginx:alpine

# Копируем статические файлы
COPY . /usr/share/nginx/html

# Копируем конфигурацию nginx (создадим позже)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]